"use client";

import Navigation from "@/components/Navigation";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import { useEffect } from "react";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My first Next App",
  description: "Generated by create next app",
  keywords: "next, react, app",
};

export default function RootLayout({ children }) {
  useEffect(() => {
    import("@/node_modules/bootstrap/dist/js/bootstrap");
  }, []);

  return (
    <html lang="en" className="h-100">
      <body className={`bg-secondary bg-gradient ${inter.className}`}>
        <Navigation />
        <div className="container p-4">{children}</div>
      </body>
    </html>
  );
}
